---
- hosts: deflux
  tasks:
    - name: fetch outflux
      get_url:
        url: https://github.com/timescale/outflux/releases/download/0.2.0/outflux_0.2.0_Linux_x86_64.tar.gz
        dest: /root
        mode: 755
    - name: install outflux
      command: tar zxvf /root/outflux_0.2.0_Linux_x86_64.tar.gz
      args:
        chdir: /usr/local/bin

